
export const COUPON_NORMAL_ACTION = 'COUPON_NORMAL_ACTION';
export const COUPON_AGAGIN_ACTION = 'COUPON_AGAGIN_ACTION';
export const COUPON_HUD_REQUEST_REDUCER = 'COUPON_HUD_REQUEST_REDUCER';
export const COUPON_PLACE_REQUEST_REDUCER = 'COUPON_PLACE_REQUEST_REDUCER';