/// 首次刷新
export const ADDRESS_NORMAL_ACTION = 'ADDRESS_NORMAL_ACTION';
/// 刷新
export const ADDRESS_HEADER_ACTION = 'ADDRESS_HEADER_ACTION';
/// 删除
export const ADDRESS_DELETE_ACTION = 'ADDRESS_DELETE_ACTION';
/// 刷新结果
export const ADDRESS_REQUEST_REDUCER = 'ADDRESS_REQUEST_REDUCER';
/// 更改刷新状态
export const ADDRESS_REFRESH_STATE_ACTION = 'ADDRESS_REFRESH_STATE_ACTION';
/// 更改HUD刷新
export const ADDRESS_HUD_STATE_ACTION = 'ADDRESS_HUD_STATE_ACTION';