
export const LOGIN_LOGIN_ACTION = 'LOGIN_LOGIN_ACTION';
export const LOGIN_LOGIN_REDUCER = 'LOGIN_LOGIN_REDUCER';
export const LOGIN_HUD_ACTION = 'LOGIN_HUD_ACTION';
export const LOGIN_NAME_ACTION = 'LOGIN_NAME_ACTION';